export const GAME_CONFIG = {
    CANVAS_WIDTH: 1000,
    CANVAS_HEIGHT: 600,
    BALL_RADIUS: 10,
    BALL_INITIAL_SPEED: 0.3,
    BALL_SPEED_INCREASE: 0.03,
    PADDLE_SPEED: 0.5,
    PADDLE_WIDTH: 15,
    PADDLE_HEIGHT: 100
};